### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Yadadye**
Did it the way you showed me.
Finished.

### CODE REVIEW

**Comment by khatchad** [comment]
Um, why is your java code in the readme file? Please resubmit in a java file as usual. Come see me for help if you need it.

**Comment by khatchad** [comment]
Closing for now. Please reopen upon re-submission.

**Comment by Yadadye** [comment]
Hey professor, I am having difficulty fixing the the saleabarchartgenerator hw, how can I re-submit it into a java file ?

**Comment by khatchad** [comment]
Please follow these steps:
1. [**Clone**](http://gitref.org/creating/#clone) the forked (this is the one with your user name in the URL) repository to your computer.
2. Modify the files and [**commit**](http://gitref.org/basic/#commit) changes to complete your solution.
3. [**Push**](http://gitref.org/remotes/#push)/sync the changes up to GitHub.
4. [Create a **pull request**](https://help.github.com/articles/creating-a-pull-request) on the original repository to turn in the assignment.

**Comment by khatchad** [comment]
Did you fix it?

**Pull request closed without merging**
